### ISSUE TITLE
suggestion: .class { clear: fix }

### ISSUE THREAD

**Issue by matthewmueller** [fgnass/rework-clearfix#1]
This is a sweet rework plugin, but I think the api is a bit strange.

1) css commands normally do not have quotes
2) optional: clear: content is more correct, but clear: fix is probably more memorable.

Just some thoughts :-D feel free to close if you disagree or if there's some other reason.

**Comment by fgnass** [comment]
Oops, 1) is a bug in the README, of course it doesn't require any quotes - I guess I just wrote too many JS object literals that day ;)

2) I like the clear:fix idea. I would suggest to support both, content and fix.

I'll fix this as soon as I'm back from vacation next week!

**Comment by matthewmueller** [comment]
<3
